name: "Download data"

on: push
  #schedule:
  #  - cron:  '0 13 * * *'

jobs:
  download-data:
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout repository"
      uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.RAJK_KEY }}
        known_hosts: 146.110.60.20:2222
    - name: Run download_data.py
      env:
        RAJK_KEY: ${{ secrets.RAJK_KEY }}
      run: |
        python download_data.py
        git config --global user.email "gh-actions@github.com"
        git config --global user.name "github actions"
